#!/usr/bin/env bash
# Prints "bad luck" on the 4th loop, "good luck" on the 8th loop and "Best School" everyother loop
i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
